input {
  file {
    path => "/app/weblog.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  if [message] =~ /^IP,/ or [message] =~ /^\s*$/ {
    drop {}
  }

  csv {
    columns => ["ip", "time", "request", "status_code"]
    separator => ","
  }

  if [ip] !~ /^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/ {
    mutate { add_tag => "quarantine" }
  }
  if [status_code] !~ /^\d{3}$/ {
    mutate { add_tag => "quarantine" }
  }

  mutate { gsub => ["time", "^\[", ""] }
  mutate { copy => { "@timestamp" => "ingested_at" } }

  date {
    match => ["time", "dd/MMM/yyyy:HH:mm:ss"]
    locale => "en"
    target => "@timestamp"
  }
  if "_dateparsefailure" in [tags] {
    mutate { add_tag => "quarantine" }
  }

  if "quarantine" not in [tags] {
    mutate {
      convert => { "status_code" => "integer" }
      remove_field => ["message", "time", "host", "path", "@version"]
    }
  }
}

output {
  if "quarantine" in [tags] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "quarantine"
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "weblogs-%{+YYYY.MM.dd}"
    }
  }

  stdout { codec => rubydebug }
}