input { 
  file {
    path => "/app/weblog.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  if [message] =~ /^IP,/ {
    drop { }
  }
  csv {
    columns => ["ip", "time", "request", "status_code"]
    separator => ","
  }
  mutate {
    gsub => ["time", "^\[", ""]
  }
  date {
    match => ["time", "dd/MMM/yyyy:HH:mm:ss"]
    locale => "en"
    target => "@timestamp"
  }
  mutate {
    convert => { "status_code" => "integer" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "weblogs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}