CREATE USER shop_admin PASSWORD 'shop_secret';
CREATE DATABASE shop OWNER shop_admin ENCODING 'UTF8' LC_COLLATE='ru_RU.utf8' LC_CTYPE='ru_RU.utf8' TEMPLATE='template0' CONNECTION LIMIT 10;
GRANT ALL PRIVILEGES ON DATABASE shop TO shop_admin;